services:
  # backend:
  #     build:
  #       dockerfile: Dockerfile
  #       context: "./back-end"
  #     image: back-end-img:1.0.0
  #     ports:
  #       - "5100:5100"
  #     volumes:
  #       - ./back-end:/ams

  client:
    build:
      dockerfile: Dockerfile
      context: '.'
    image: front-end-img:1.0.0
    ports:
      - '3000:3000'
    volumes:
      - .:/ECommerce
